research_task:
  description: >
    {topic}에 대해 최신 정보와 동향을 철저하게 연구하여 가장 중요한 요소를 찾아내세요.
    {current_date} 현재를 기준으로, {topic}에 대한 신뢰할 수 있는 출처에서만 최신 정보를 가져오세요.

  expected_output: >
    1. 신뢰할 수 있는 금융 및 경제 뉴스 사이트에서 검색된 최신 트렌드 정리 (예: Bloomberg, Reuters, WSJ)
    2. 해당 정보를 기반으로 10가지 주요 사항을 정리
    3. 출처 명확하게 명시 (예: "Bloomberg 기사에 따르면...")

  agent: researcher

reporting_task:
  description: >
    받은 자료를 검토하고 각 주제를 리포트의 전체 섹션으로 확장하세요.
    리포트는 상세하고 관련된 모든 정보를 포함해야 하며, 마크다운 형식으로 작성되어야 합니다.
    {current_date} 기준 최신 시장 트렌드를 포함해야 합니다.

  expected_output: >
    0. 한글로 작성할것
    1. 최신 금융 데이터 및 트렌드를 기반으로 10가지 주요 사항 정리
    2. 리포트 형식은 다채롭고 전문적인 가독성이 뛰어난 마크다운 언어로 작성되야함

  agent: reporting_analyst
