services:
  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # 로컬 코드와 컨테이너 코드 동기화
      - /app/node_modules  # node_modules를 컨테이너 내부에서 관리
    environment:
      - VITE_DEV_SERVER_HMR_HOST=host.docker.internal # Docker 호스트에 연결
      - VITE_DEV_SERVER_HMR_PORT=3000                # WebSocket 포트 설정
      - CHOKIDAR_USEPOLLING=true

      - NODE_ENV=development
    command: yarn vite --host 0.0.0.0  # Vite 개발 서버 실행

  django:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # 로컬 코드와 컨테이너 코드 동기화
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn -k uvicorn.workers.UvicornWorker --reload TradeVortex.asgi:application --bind 0.0.0.0:8000 --workers 4
