# Generated by Django 5.1.4 on 2025-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialdata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='financialdata',
            constraint=models.UniqueConstraint(fields=('symbol', 'timestamp'), name='unique_symbol_timestamp'),
        ),
    ]
