# Generated by Django 5.1.4 on 2025-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
