# Generated by Django 5.1.4 on 2025-02-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0002_newsitem_is_duplicate_newsitem_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
