research_task:
  description: >
    {topic}에 대해 최신 정보와 동향을 철저하게 연구하여 가장 중요한 요소를 찾아내세요.
    2025년 현재를 기준으로, {topic}에 대한 흥미롭고 관련성 있는 정보를 최신 동향에 맞춰 제공하세요.
  expected_output: >
    {topic}에 대한 가장 중요한 10가지 정보를 나열하세요. 주식이나 암호화폐와 같은 금융 분야에 대해서는 최근 상승 또는 하락을 보이는 종목 및 트렌드를 포함하세요.
  agent: researcher

reporting_task:
  description: >
    받은 자료를 검토하고 각 주제를 리포트의 전체 섹션으로 확장하세요.
    리포트는 상세하고 관련된 모든 정보를 포함해야 하며, 마크다운 형식으로 작성되어야 합니다.
  expected_output: >
    주제에 대해 각각의 세부 섹션이 포함된 전체 리포트를 작성하세요. 
    최신 시장 트렌드와 데이터를 반영해야 합니다. 
    작성 될 리포트는 글자 굵기 등 가독성이 뛰어나며 아름다워야 합니다.
    예: '현재 상승하는 주식' 또는 '가장 주목받는 암호화폐' 등 주제별 상세 정보 제공.
    리포트는 무조건 한국어로 작성되야 하며.
    # **리포트 제목**

    ## **서론**

    내용
    
    ---
    (이하 내용)
    과 같이 작성하세요

  agent: reporting_analyst
